name: Pull Request Workflow
on:
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
          level: warning
          reporter: github-pr-review
          fail_on_error: true

  languagetool:
    name: languagetool job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-languagetool@v1
        with:
          reporter: github-pr-review
          level: info

  shellcheck:
    name: shellcheck job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: true

  alex:
    name: alex job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review
          level: info